### PR TITLE
Transfer pipelines to new drone

### PR DESCRIPTION
**Pull request by tasharnvb**

### CODE REVIEW

**Review by KashifSaadat — APPROVED** [review]
LGTM

**Comment by daniel-ac-martin** [comment]
Have the secrets been migrated?

**Comment by easternbloc** [comment]
@tasharnvb @KashifSaadat please respond to Daniel's question.

**Comment by KashifSaadat** [comment]
Yep the secrets were re-created and pipeline validated in the new drone deployment.

**Comment by tasharnvb** [comment]
Sorry! I didn't see the question on Friday and I haven't been able to double check that I added them today because (acp) drone is down at the moment.

**Comment by tasharnvb** [comment]
I've just double checked and yes the secret has been migrated.

**Review by daniel-ac-martin — APPROVED** [review]

**Pull request merged**
